let createImageData = "";
let createPdfText = "";
let lastCreatePrompt = "";

function setCreateStatus(text, mode = "info") {
    const el = document.getElementById("createStatus");
    if (!el) return;
    el.textContent = text;
    el.dataset.mode = mode;
}

function readFileAsDataUrl(file) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result);
        reader.onerror = reject;
        reader.readAsDataURL(file);
    });
}

async function extractCreatePdf(file) {
    if (!window.pdfjsLib) throw new Error("PDF reader is not loaded yet.");
    const buffer = await file.arrayBuffer();
    const pdf = await pdfjsLib.getDocument(new Uint8Array(buffer)).promise;
    let text = "";
    for (let i = 1; i <= pdf.numPages; i++) {
        const page = await pdf.getPage(i);
        const content = await page.getTextContent();
        text += `\n--- PDF page ${i} ---\n${content.items.map(item => item.str).join(" ")}`;
    }
    return text.trim().slice(0, 5000);
}

async function describeCreateReference() {
    if (!createImageData) return "";
    setCreateStatus("🖼️ Reading the uploaded image for visual details...", "loading");
    const res = await fetch("/api/gemini-vision", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
            imageBase64: createImageData,
            userPrompt: "Describe this image as visual guidance for a new AI image generation prompt. Mention subject, style, colors, layout, mood, and any visible text."
        })
    });
    const data = await res.json();
    if (!res.ok) throw new Error(data.error || "Could not read reference image.");
    return data.text || "";
}

async function generateCloudflareImage() {
    const promptBox = document.getElementById("createPrompt");
    const btn = document.getElementById("createGenerateBtn");
    const prompt = promptBox ? promptBox.value.trim() : "";
    if (!prompt && !createImageData && !createPdfText) return setCreateStatus("⚠️ Add a prompt, image, or PDF first.", "error");

    btn.disabled = true;
    btn.innerHTML = "<span class='spinner'></span> Generating...";
    document.getElementById("createClearBtn").style.display = "flex";

    try {
        const referenceText = await describeCreateReference();
        lastCreatePrompt = [
            prompt ? `USER PROMPT:\n${prompt}` : "",
            createPdfText ? `PDF CONTEXT:\n${createPdfText}` : "",
            referenceText ? `REFERENCE IMAGE DETAILS:\n${referenceText}` : "",
            "Create one high quality, polished, decorative image. Keep text readable, avoid clutter, and stay inside image borders."
        ].filter(Boolean).join("\n\n");

        setCreateStatus("☁️ Sending final prompt to Cloudflare image generation...", "loading");
        const res = await fetch("/api/cloudflare-image", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ prompt: lastCreatePrompt })
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error || "Cloudflare image generation failed.");

        const imageUrl = data.image || `data:image/png;base64,${data.base64}`;
        document.getElementById("createResultStage").innerHTML = `<img class="creator-output-img" src="${imageUrl}" alt="Generated Cloudflare artwork">`;
        document.getElementById("downloadCreatedImage").href = imageUrl;
        document.getElementById("createActions").style.display = "grid";
        setCreateStatus(`✅ Image generated by ${data.provider || "Cloudflare"}.`, "success");
        saveCreateHistory(prompt || "Image Creator request", imageUrl);
    } catch (error) {
        setCreateStatus("❌ " + error.message, "error");
    } finally {
        btn.disabled = false;
        btn.innerHTML = "✨ Generate Image";
    }
}

function saveCreateHistory(question, imageUrl) {
    try {
        const history = JSON.parse(localStorage.getItem("aiHistory") || "[]");
        history.unshift({
            id: Date.now(),
            type: "create",
            title: "Image Creator",
            createdAt: new Date().toISOString(),
            interactions: [{ question, answer: "Generated Cloudflare image", image: imageUrl, provider: "Cloudflare" }]
        });
        localStorage.setItem("aiHistory", JSON.stringify(history.slice(0, 80)));
    } catch (e) {}
}

function clearCreateInputs() {
    createImageData = "";
    createPdfText = "";
    lastCreatePrompt = "";
    document.getElementById("createPrompt").value = "";
    document.getElementById("createImageInput").value = "";
    document.getElementById("createPdfInput").value = "";
    document.getElementById("createImageName").textContent = "Reference / inspiration";
    document.getElementById("createPdfName").textContent = "Use notes / document text";
    document.getElementById("createImagePreview").style.display = "none";
    document.getElementById("createPdfPreview").style.display = "none";
    document.getElementById("createClearBtn").style.display = "none";
    setCreateStatus("Ready. Add your prompt and optional files.");
}

function copyCreatedPrompt() {
    navigator.clipboard?.writeText(lastCreatePrompt || document.getElementById("createPrompt").value || "");
    setCreateStatus("📋 Final generation prompt copied.", "success");
}

function toggleSidebar() {
    const sidebar = document.getElementById("sidebar");
    const overlay = document.getElementById("overlay");
    const active = !sidebar.classList.contains("active");
    sidebar.classList.toggle("active", active);
    overlay.classList.toggle("active", active);
    document.body.classList.toggle("sidebar-open", active);
}

window.generateCloudflareImage = generateCloudflareImage;
window.clearCreateInputs = clearCreateInputs;
window.copyCreatedPrompt = copyCreatedPrompt;
window.toggleSidebar = toggleSidebar;

document.addEventListener("DOMContentLoaded", () => {
    document.getElementById("overlay").onclick = toggleSidebar;
    document.getElementById("createImageInput").addEventListener("change", async (event) => {
        const file = event.target.files[0];
        if (!file) return;
        createImageData = await readFileAsDataUrl(file);
        document.getElementById("createImageName").textContent = file.name;
        const preview = document.getElementById("createImagePreview");
        preview.src = createImageData;
        preview.style.display = "block";
        document.getElementById("createClearBtn").style.display = "flex";
        setCreateStatus("✅ Reference image attached.", "success");
    });
    document.getElementById("createPdfInput").addEventListener("change", async (event) => {
        const file = event.target.files[0];
        if (!file) return;
        try {
            setCreateStatus("📄 Reading PDF text...", "loading");
            createPdfText = await extractCreatePdf(file);
            document.getElementById("createPdfName").textContent = file.name;
            document.getElementById("createPdfPreview").style.display = "block";
            document.getElementById("createClearBtn").style.display = "flex";
            setCreateStatus("✅ PDF context attached.", "success");
        } catch (error) {
            setCreateStatus("❌ " + error.message, "error");
        }
    });
});
